In [1]:
from hangman_predictor import get_top_predictions
get_top_predictions(guessed_letters, current_state, top_n=5)

Loading model from checkpoints/checkpoint-15000
cuda


In [2]:
guessed_letters = ["a"]
current_state = ["a", "*"]

sequence = list(guessed_letters) + ['[SEP]'] + list(current_state)
sequence

['a', '[SEP]', 'a', '*']

In [15]:
get_top_predictions(guessed_letters, current_state, top_n=5)

[{'letter': 'd', 'probability': 0.07493946701288223},
 {'letter': 'm', 'probability': 0.06664960831403732},
 {'letter': 's', 'probability': 0.06587589532136917},
 {'letter': 'r', 'probability': 0.06410318613052368},
 {'letter': 't', 'probability': 0.06046698987483978}]

In [11]:
predict_next_letter(guessed_letters, current_state)

{'a': 0.0,
 'b': 0.05710053816437721,
 'c': 0.04155050590634346,
 'd': 0.07493946701288223,
 'e': 0.010375890880823135,
 'f': 0.039231326431035995,
 'g': 0.03854186087846756,
 'h': 0.04029024392366409,
 'i': 0.028934285044670105,
 'j': 0.031069345772266388,
 'k': 0.023570071905851364,
 'l': 0.05657320097088814,
 'm': 0.06664960831403732,
 'n': 0.059762123972177505,
 'o': 0.016207408159971237,
 'p': 0.04188334941864014,
 'q': 0.008851277641952038,
 'r': 0.06410318613052368,
 's': 0.06587589532136917,
 't': 0.06046698987483978,
 'u': 0.02354707382619381,
 'v': 0.04879368469119072,
 'w': 0.0467037595808506,
 'x': 0.020208610221743584,
 'y': 0.015452648513019085,
 'z': 0.01843416690826416}

In [3]:
input_ids = tokenizer.encode(sequence)

In [4]:
input_ids

array([ 0, 28,  0, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27])

In [5]:
input_tensor = torch.tensor(input_ids, dtype=torch.long).unsqueeze(0).to(device)

In [6]:
input_tensor

tensor([[ 0, 28,  0, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
         27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
         27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27]],
       device='cuda:0')

In [10]:
model(input_tensor)["probs"]*100

tensor([[0.0883, 5.7101, 4.1551, 7.4939, 1.0376, 3.9231, 3.8542, 4.0290, 2.8934,
         3.1069, 2.3570, 5.6573, 6.6650, 5.9762, 1.6207, 4.1883, 0.8851, 6.4103,
         6.5876, 6.0467, 2.3547, 4.8794, 4.6704, 2.0209, 1.5453, 1.8434]],
       device='cuda:0', grad_fn=<MulBackward0>)